ARG LINUX_DISTR=rockylinux/rockylinux
ARG LINUX_DISTR_VER=9.8
FROM $LINUX_DISTR:$LINUX_DISTR_VER

ARG SITE_MIRROR
ARG LC_ALL=en_US.UTF-8
ARG LANG=en_US.UTF-8
ARG LANGUAGE=en_US.UTF-8

ENV USER root
ENV HOME /root
ENV CONTRAIL $HOME/contrail
ENV LC_ALL=$LC_ALL
ENV LANG=$LANG
ENV LANGUAGE=$LANGUAGE
ENV PS1="sandbox:\[\033[01;34m\]\w\[\033[00m\]\$ "

WORKDIR $CONTRAIL

# Inject repositories that we might need
# copy pip.conf to the same place and move it to right place later to simplify build script
COPY *.repo pip.conf* /etc/yum.repos.d/
COPY entrypoint.sh build-rocky*.sh /

RUN source /etc/os-release && /build-rocky$(echo ${VERSION_ID} | cut -d '.' -f 1).sh

ENTRYPOINT ["/entrypoint.sh"]
